apiVersion: json.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  annotations:
    description.policy.kyverno.io: This Policy ensures that FARGATE clusters have container insights enabled.
    title.policy.kyverno.io: Norvatis requires FARGATE usage
    policies.kyverno.io/category: ECS Best Practices
  labels:
    ecs.aws.tags.kyverno.io: ecs-cluster
  name: ecs-cluster-require-fargate
spec:
  rules:
    - name: required-container-fargate
      identifier: |-
        (
          resources[0] ||
          detail.responseElements.service.serviceArn ||
          detail.responseElements.taskDefinition.taskDefinitionArn ||
          detail.responseElements.tasks[0].taskArn ||
          detail.containerInstanceArn ||
          detail.clusterArn ||
          ''
        )
      match:
        all:
         - source: aws.ecs
         - detail-type: "ECS Task State Change"
         - detail:
             (contains(desiredStatus, 'STOPPED')): false
      assert:
        all:
          - message: ECS Cluster use of Fargate or Fargate Spot instances should not be used at '{{detail.requestParameters.taskDefinition}}'
            check:
              detail:
                launchType:
                  (contains(@, 'FARGATE') || contains(@, 'FARGATE SPOT')): false
