apiVersion: json.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: validate-ecs-task-and-definition-memory-hard-limit
  # labels:
  #   ecs.aws.tags.kyverno.io: 'ecs-task'
  annotations:
    policies.kyverno.io/title: Validate ECS Task Definition Memory Hard Limit
    policies.kyverno.io/category: ECS Best Practices
    policies.kyverno.io/severity: low
    policies.kyverno.io/description: >-
      This policy checks if Amazon Elastic Container Service
      (ECS) task definitions and tasks have a set memory limit for its container definitions.
      If a memory limit is not set for a container, it can consume excessive memory, potentially starving other containers running on the same host.
      Therefore, it is crucial to enforce a hard memory limit on each container to prevent resource contention.
      If a container exceeds its memory limit, it will be terminated by ECS.
spec:
  rules:
    - name: validate-ecs-task-memory-hard-limit
      match:
        all:
         - source: aws.ecs
         - detail-type: "ECS Task State Change"
         - detail:
            lastStatus: 'PROVISIONING'
      assert:
        all:
          - message: From Lambda - Memory limit for containers in the task should be set in the container definitions of its task
            check:
              detail:
                ~.(containers):
                    (!memory): false
