apiVersion: json.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: ecs-service-check-public-ip-lambda
  labels:
    ecs.aws.tags.kyverno.io: 'ecs-service'
  annotations:
    title.policy.kyverno.io: ECS service check public IP
    description.policy.kyverno.io: This Policy checks that ECS service does not use a public IP
    policies.kyverno.io/category: ECS Best Practices
spec:
  rules:
    - name: ecs-service-check-public-ip
      identifier: |-
        (
          resources[0] ||
          detail.responseElements.service.serviceArn ||
          detail.responseElements.taskDefinition.taskDefinitionArn ||
          detail.responseElements.tasks[0].taskArn ||
          detail.containerInstanceArn ||
          detail.clusterArn ||
          ''
        )
      match:
        all:
         - source: aws.ecs
         - detail-type: "AWS API Call via CloudTrail"
         - detail:
             (contains(eventName, 'CreateService')): true
      assert:
        all:
          - message: "ECS Services '{{detail.requestParameters.serviceName}}' should not use public IP"
            check:
              detail:
                responseElements:
                  service:
                    ~.deployments:
                      networkConfiguration:
                        awsvpcConfiguration:
                          assignPublicIp: DISABLED
