apiVersion: json.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: validate-ecs-container-insights-enabled
  annotations:
    policies.kyverno.io/title: Validate ECS Container Insights are Enabled
    policies.kyverno.io/category: ECS Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/description: >-
      Container Insights enhances the operational visibility of ECS clusters, allowing for proactive issue resolution.
      Enabling this feature ensures that diagnostic information is readily available, contributing to a more efficient and reliable containerized environment.
spec:
  rules:
    - name: validate-ecs-container-insights-enabled
      match:
        all:
         - source: aws.ecs
         - detail-type: "AWS API Call via CloudTrail"
         - detail:
             (contains(eventName, 'UpdateClusterSettings')): true
      assert:
        all:
          - message: "ECS container insights must be enabled"
            check:
              detail:
                responseElements:
                  cluster:
                    ~.(setting):
                      (name != 'containerInsights' || value == 'enabled'): true
