{{ range $name, $secret := .Values.imagePullSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "admission-controller.fullname" $ }}-{{ $name }}
  namespace: {{ template "admission-controller.namespace" $ }}
  labels:
    control-plane: controller-manager
  {{- include "admission-controller.labels" $ | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "admission-controller.config.imagePullSecret" $secret }}
{{ end }}
