{{- if .Values.metricsService.createServiceMonitor }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "admission-controller.fullname" . }}-metrics-service
  namespace: {{ template "admission-controller.namespace" . }}
  labels:
    control-plane: controller-manager
  {{- include "admission-controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    control-plane: controller-manager
  {{- include "admission-controller.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.metricsService.ports | toYaml | nindent 2 }}
{{- end }}
