apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "admission-controller.fullname" . }}-proxy-viewer-role
  labels:
  {{- include "admission-controller.labels" . | nindent 4 }}
rules:
- apiGroups:
  - proxy.nirmata.io
  resources:
  - proxies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - proxy.nirmata.io
  resources:
  - proxies/status
  verbs:
  - get