apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "admission-controller.fullname" . }}
  namespace: {{ template "admission-controller.namespace" . }}
  labels:
  {{- include "admission-controller.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}