#!/bin/bash
# Build for ARM64
# Builder
FROM amazon/aws-lambda-nodejs:18
RUN yum -y update && yum -y install unzip && yum clean all

RUN curl -sSL https://nirmata-downloads.s3.us-east-2.amazonaws.com/nctl/nctl_3.3.9/nctl_3.3.9_linux_64-bit.zip  -o nctl.zip &&  unzip nctl.zip && mv nctl /bin

COPY ./src/app.js ./src/package*.json ./
RUN npm install && npm install -g js-yaml
RUN mkdir /policies
COPY ./test/policy/verify-ecs-image.yaml /policies/
ENV HOME=/tmp

CMD [ "app.handler" ]
