apiVersion: json.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  annotations:
    description.policy.kyverno.io: This Policy ensures that FARGATE clusters have container insights enabled.
    title.policy.kyverno.io: Norvatis requires FARGATE usage
  labels:
    ecs.aws.tags.kyverno.io: ecs-cluster
  name: ecs-cluster-require-fargate
spec:
  rules:
    - name: required-container-fargate
      assert:
        any:
          - message: ECS Cluster use of Fargate or Fargate Spot instances should be used '{{clusterName}}' at '{{clusterArn}}'
            check:
              capacityProviders:
                (contains(@, 'FARGATE')): true
                (contains(@, 'FARGATE_SPOT')): true
