apiVersion: json.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: ecs-service-check-public-ip
  labels:
    ecs.aws.tags.kyverno.io: 'ecs-cluster'
  annotations:
    title.policy.kyverno.io: ECS service check public IP
    description.policy.kyverno.io: This Policy checks that ECS service does not use a public IP
spec:
  rules:
    - name: ecs-service-check-public-ip
      match:
        all:
         - source: aws.ecs
         - detail-type: "AWS API Call via CloudTrail"
         - detail:
             (contains(eventName, 'RunTask') || contains(eventName, 'CreateTask')): true
      assert:
        all:
        - message: "ECS Services '{{detail.requestParameters.serviceName}}' should not use public IP"
          check:
            detail:
              requestParameters:
                networkConfiguration:
                  awsvpcConfiguration:
                    assignPublicIp: DISABLED
