apiVersion: json.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  annotations:
    description.policy.kyverno.io: This Policy ensures that ECS services do not have public Docker image
    title.policy.kyverno.io: ECS Task Definition public Docker Image usage
    policies.kyverno.io/category: ECS Best Practices
  labels:
    ecs.aws.tags.kyverno.io: ecs-task-definition
  name: ecs-task-definition-ro-root-fs
spec:
  rules:
    - name: ecs-task-definition-ro-root-fs
      identifier: |-
        (
          resources[0] ||
          detail.responseElements.service.serviceArn ||
          detail.responseElements.taskDefinition.taskDefinitionArn ||
          detail.responseElements.tasks[0].taskArn ||
          detail.containerInstanceArn ||
          detail.clusterArn ||
          ''
        )
      match:
        all:
         - source: aws.ecs
         - detail-type: "AWS API Call via CloudTrail"
         - detail:
             (contains(eventName, 'RegisterTaskDefinition') || contains(eventName, 'CreateTaskDefinition')): true
      assert:
        any:
          - message: ECS Task Definitions require the use of readonlyRootFilesystem at '{{detail.responseElements.taskDefinitionArn}}'
            check:
              detail:
                requestParameters:
                  ~.containerDefinitions:
                    readonlyRootFilesystem: false
