apiVersion: json.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  annotations:
    description.policy.kyverno.io: This Policy ensures that ECS services do not allow container 'command' overrides
    title.policy.kyverno.io: ECS Task does not allow container 'command' overrides
    policies.kyverno.io/category: ECS Best Practices
  labels:
    ecs.aws.tags.kyverno.io: ecs-task
  name: ecs-task-container-command
spec:
  rules:
    - name: ecs-task-container-command
      identifier: |-
        (
          resources[0] ||
          detail.responseElements.service.serviceArn ||
          detail.responseElements.taskDefinition.taskDefinitionArn ||
          detail.responseElements.tasks[0].taskArn ||
          detail.containerInstanceArn ||
          detail.clusterArn ||
          ''
        )
      match:
        all:
         - source: aws.ecs
         - detail-type: "ECS Task State Change"
         - detail:
             (contains(desiredStatus, 'STOPPED')): false
      assert:
        any:
          - message: ECS Tasks does not allow overriding container 'command' at task '{{detail.taskArn}}'
            check:
              detail:
                overrides:
                  ~.containerOverrides:
                    # Make sure that 'command' is not set
                    (!command): true
