name: Periodic scan of AWS ECS Resources with NCTL
on:
  # schedule:
  #   - cron: "0/15 * * * *"
  workflow_dispatch:

env:
  AWS_REGION: us-west-1

permissions:
  contents: read

jobs:
  pull-aws-resources:
    name: Periodic AWS ECS Resource Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: sagarsthorat/aws-cli@v1
      with:
        region: ${{ env.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        output-format: json

    - name: Install NCTL
      run: |
        echo "Downloading and Installing NCTL 4.1.0"
        wget https://nirmata-downloads.s3.us-east-2.amazonaws.com/nctl/nctl_4.2.1-rc.7/nctl_4.2.1-rc.7_linux_amd64.zip
        unzip -o *.zip
        echo "Verify Installation"
        chmod 755 ./nctl
        ./nctl version
        ./nctl login --url https://nirmata.io --userid boris.kurktchiev@nirmata.com --token ${{ secrets.NPM_TOKEN }}

    - name: Setup Payload directory
      run: mkdir payloads

    - name: Pull down current clusters
      run: aws ecs describe-clusters --output json --region ${{ env.AWS_REGION }} --include SETTINGS --clusters `aws ecs list-clusters --query clusterArns --output text --region ${{ env.AWS_REGION }}` > payloads/$(date +%Y%m%d%H%M%S)-cluster-list.json

    - name: Pull down current tasks per cluster
      run: |
        runtime=$(date +%Y%m%d%H%M%S)
        for i in $(aws ecs list-clusters --query clusterArns --output text --region ${{ env.AWS_REGION }}); do
          count=$((count+1))
          aws ecs list-tasks --query taskArns --output text --cluster ${i} --region ${{ env.AWS_REGION }} > payloads/${runtime}-${count}-task-count.txt
          if (($(cat payloads/${runtime}-${count}-task-count.txt | wc -l) > 0 )); then
            aws ecs describe-tasks --output json --cluster ${i} --region ${{ env.AWS_REGION }} --tasks `cat payloads/${runtime}-${count}-task-count.txt` > payloads/${runtime}-${count}-task-list.json
          fi
        done

    - name: Check with NCTL
      run: ./nctl scan json -p cicd/ -r payloads/ --details --publish --report-sourceid=$(date +%Y%m%d%H%M%S)

    # - name: Check tasks with NCTL
    #   run: ./nctl scan json -p policies/ -r *-task-list.json --details --publish
