name: Scan Terraform on new code push
on:
  push:
    paths:
      - 'terraform/config/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pull-aws-resources:
    name: Scan Terraform
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install NCTL
      run: |
        echo "Downloading and Installing NCTL 4.1.0"
        wget https://nirmata-downloads.s3.us-east-2.amazonaws.com/nctl/nctl_4.2.1-rc.7/nctl_4.2.1-rc.7_linux_amd64.zip
        unzip -o *.zip
        echo "Verify Installation"
        chmod 755 ./nctl
        ./nctl version
        ./nctl login --url https://nirmata.io --userid boris.kurktchiev@nirmata.com --token ${{ secrets.NPM_TOKEN }}

    - name: Check with NCTL
      run: ./nctl scan terraform -p terraform/policies/ -r terraform/configs --details --audit-as-warn --publish --report-sourceid=$(date +%Y%m%d%H%M%S)
